# Generated by Django 5.0.6 on 2024-06-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='noimage.png', null=True, upload_to='products/'),
        ),
    ]
