# Generated by Django 5.0.6 on 2024-06-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to='products/'),
        ),
    ]
