# Generated by Django 5.0.6 on 2024-06-19 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_category_alter_course_image_course_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
    ]
