# Generated by Django 5.0.6 on 2024-06-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_title_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='courses',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='courses',
            field=models.ManyToManyField(to='courses.course'),
        ),
    ]
